# Generated by Django 3.2.9 on 2021-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
